export const users = [
  {
    id: 1,
    name: "Guddu",
    email: "pandit@gmail.com",
    age: "32",
    city: "Mirzapur",
  },
  {
    id: 2,
    name: "Bablu",
    email: "tripathi@gmail.com",
    age: "30",
    city: "Jaunpur",
  },
  {
    id: 3,
    name: "Munna",
    email: "bhau@gmail.com",
    age: "28",
    city: "Mirzapur",
  },
  {
    id: 4,
    name: "Golu",
    email: "gupta@gmail.com",
    age: "26",
    city: "Kanpur",
  },
  {
    id: 5,
    name: "Beena",
    email: "tripathi.b@gmail.com",
    age: "34",
    city: "Lucknow",
  },
  {
    id: 6,
    name: "Rati",
    email: "shukla@gmail.com",
    age: "29",
    city: "Allahabad",
  },
  {
    id: 7,
    name: "Sharad",
    email: "shrivastava@gmail.com",
    age: "33",
    city: "Varanasi",
  },
  {
    id: 8,
    name: "Sweety",
    email: "gupta.s@gmail.com",
    age: "27",
    city: "Mirzapur",
  },
  {
    id: 9,
    name: "Ramakant",
    email: "yadav@gmail.com",
    age: "50",
    city: "Azamgarh",
  },
  {
    id: 10,
    name: "Shankar",
    email: "shukla.s@gmail.com",
    age: "42",
    city: "Ballia",
  },
  {
    id: 11,
    name: "Lala",
    email: "lalan@gmail.com",
    age: "35",
    city: "Patna",
  },
  {
    id: 12,
    name: "Sweety",
    email: "sweety@gmail.com",
    age: "27",
    city: "Varanasi",
  },
  {
    id: 13,
    name: "Vinod",
    email: "vinod@gmail.com",
    age: "38",
    city: "Gorakhpur",
  },
  {
    id: 14,
    name: "Pinky",
    email: "pinky@gmail.com",
    age: "22",
    city: "Lucknow",
  },
  {
    id: 15,
    name: "Kaleen",
    email: "kaleen@gmail.com",
    age: "45",
    city: "Mirzapur",
  },
  {
    id: 16,
    name: "Radha",
    email: "radha@gmail.com",
    age: "31",
    city: "Prayagraj",
  },
  {
    id: 17,
    name: "Vikrant",
    email: "vikrant@gmail.com",
    age: "29",
    city: "Noida",
  },
  {
    id: 18,
    name: "Ajay",
    email: "ajay@gmail.com",
    age: "34",
    city: "Agra",
  },
  {
    id: 19,
    name: "Seema",
    email: "seema@gmail.com",
    age: "27",
    city: "Jaipur",
  },
  {
    id: 20,
    name: "Kiran",
    email: "kiran@gmail.com",
    age: "32",
    city: "Bhopal",
  },
  {
    id: 21,
    name: "Ravi",
    email: "ravi@gmail.com",
    age: "30",
    city: "Indore",
  },
  {
    id: 22,
    name: "Deepak",
    email: "deepak@gmail.com",
    age: "36",
    city: "Gwalior",
  },
  {
    id: 23,
    name: "Pooja",
    email: "pooja@gmail.com",
    age: "28",
    city: "Jabalpur",
  },
  {
    id: 24,
    name: "Sandeep",
    email: "sandeep@gmail.com",
    age: "39",
    city: "Nagpur",
  },
  {
    id: 25,
    name: "Sunita",
    email: "sunita@gmail.com",
    age: "33",
    city: "Pune",
  },
  {
    id: 26,
    name: "Ramesh",
    email: "ramesh@gmail.com",
    age: "41",
    city: "Mumbai",
  },
  {
    id: 27,
    name: "Arun",
    email: "arun@gmail.com",
    age: "37",
    city: "Chennai",
  },
  {
    id: 28,
    name: "Suresh",
    email: "suresh@gmail.com",
    age: "35",
    city: "Hyderabad",
  },
  {
    id: 29,
    name: "Meena",
    email: "meena@gmail.com",
    age: "25",
    city: "Bangalore",
  },
  {
    id: 30,
    name: "Anita",
    email: "anita@gmail.com",
    age: "32",
    city: "Kolkata",
  },
  {
    id: 31,
    name: "Mohan",
    email: "mohan@gmail.com",
    age: "28",
    city: "Delhi",
  },
  {
    id: 32,
    name: "Nikita",
    email: "nikita@gmail.com",
    age: "29",
    city: "Gurgaon",
  },
  {
    id: 33,
    name: "Suraj",
    email: "suraj@gmail.com",
    age: "34",
    city: "Faridabad",
  },
  {
    id: 34,
    name: "Raju",
    email: "raju@gmail.com",
    age: "40",
    city: "Ghaziabad",
  },
  {
    id: 35,
    name: "Gaurav",
    email: "gaurav@gmail.com",
    age: "27",
    city: "Ahmedabad",
  },
  {
    id: 36,
    name: "Ritika",
    email: "ritika@gmail.com",
    age: "24",
    city: "Surat",
  },
  {
    id: 37,
    name: "Rahul",
    email: "rahul@gmail.com",
    age: "31",
    city: "Rajkot",
  },
  {
    id: 38,
    name: "Rohit",
    email: "rohit@gmail.com",
    age: "26",
    city: "Vadodara",
  },
  {
    id: 39,
    name: "Ragini",
    email: "ragini@gmail.com",
    age: "28",
    city: "Nashik",
  },
  {
    id: 40,
    name: "Jatin",
    email: "jatin@gmail.com",
    age: "33",
    city: "Aurangabad",
  },
  {
    id: 41,
    name: "Dinesh",
    email: "dinesh@gmail.com",
    age: "37",
    city: "Solapur",
  },
  {
    id: 42,
    name: "Madhuri",
    email: "madhuri@gmail.com",
    age: "35",
    city: "Thane",
  },
  {
    id: 43,
    name: "Nilesh",
    email: "nilesh@gmail.com",
    age: "39",
    city: "Navi Mumbai",
  },
  {
    id: 44,
    name: "Kavita",
    email: "kavita@gmail.com",
    age: "28",
    city: "Amritsar",
  },
  {
    id: 45,
    name: "Suman",
    email: "suman@gmail.com",
    age: "29",
    city: "Ludhiana",
  },
  {
    id: 46,
    name: "Vikas",
    email: "vikas@gmail.com",
    age: "32",
    city: "Chandigarh",
  },
  {
    id: 47,
    name: "Harish",
    email: "harish@gmail.com",
    age: "41",
    city: "Jalandhar",
  },
  {
    id: 48,
    name: "Neha",
    email: "neha@gmail.com",
    age: "36",
    city: "Panchkula",
  },
  {
    id: 49,
    name: "Sanjay",
    email: "sanjay@gmail.com",
    age: "38",
    city: "Shimla",
  },
  {
    id: 50,
    name: "Monika",
    email: "monika@gmail.com",
    age: "27",
    city: "Dehradun",
  },
  {
    id: 51,
    name: "Rajesh",
    email: "rajesh@gmail.com",
    age: "45",
    city: "Ranchi",
  },
  {
    id: 52,
    name: "Sneha",
    email: "sneha@gmail.com",
    age: "26",
    city: "Bhubaneswar",
  },
  {
    id: 53,
    name: "Arjun",
    email: "arjun@gmail.com",
    age: "34",
    city: "Cuttack",
  },
  {
    id: 54,
    name: "Pritam",
    email: "pritam@gmail.com",
    age: "29",
    city: "Jamshedpur",
  },
  {
    id: 55,
    name: "Vandana",
    email: "vandana@gmail.com",
    age: "31",
    city: "Dhanbad",
  },
  {
    id: 56,
    name: "Kamal",
    email: "kamal@gmail.com",
    age: "33",
    city: "Asansol",
  },
  {
    id: 57,
    name: "Usha",
    email: "usha@gmail.com",
    age: "40",
    city: "Siliguri",
  },
  {
    id: 58,
    name: "Anil",
    email: "anil@gmail.com",
    age: "28",
    city: "Durgapur",
  },
  {
    id: 59,
    name: "Tara",
    email: "tara@gmail.com",
    age: "30",
    city: "Bokaro",
  },
  {
    id: 60,
    name: "Nisha",
    email: "nisha@gmail.com",
    age: "27",
    city: "Guwahati",
  },
];
